name: Release to NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to release'
        required: true

permissions:
  contents: read
  actions: read

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PACKAGE_DIRECTORY: ./nupkg

    steps:
    - name: Download package artefacts
      uses: dawidd6/action-download-artifact@v9
      with:
        name: nuget-package-${{ inputs.version }}
        workflow: ci.yml
        path: ${{ env.PACKAGE_DIRECTORY }}
        search_artifacts: true
        if_no_artifact_found: fail

    - name: Publish to NuGet
      run: >
        dotnet nuget push
        ${{ env.PACKAGE_DIRECTORY }}/*.nupkg
        --source ${{ vars.NUGET_REPOSITORY }}
        --api-key ${{ secrets.NUGET_API_KEY }}
